# Generated by Django 6.0.5 on 2026-05-18 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='nome do pet')),
                ('categoria', models.CharField(choices=[('perdido', 'Perdido'), ('encontrado', 'Encontrado'), ('adocao', 'Adoção')], max_length=20)),
                ('foto', models.ImageField(upload_to='pets/')),
                ('raca', models.CharField(blank=True, max_length=100, verbose_name='raça')),
                ('idade', models.CharField(blank=True, max_length=60)),
                ('porte', models.CharField(choices=[('pequeno', 'Pequeno'), ('medio', 'Médio'), ('grande', 'Grande')], max_length=20)),
                ('bairro', models.CharField(max_length=120)),
                ('cidade', models.CharField(max_length=120)),
                ('data_perdido', models.DateField(blank=True, null=True, verbose_name='data em que desapareceu')),
                ('caracteristicas', models.TextField(verbose_name='características específicas')),
                ('telefone', models.CharField(max_length=30, verbose_name='número para contato')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição opcional')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'pet',
                'verbose_name_plural': 'pets',
                'ordering': ['-criado_em'],
            },
        ),
    ]
