# Generated by Django 6.0.5 on 2026-05-16 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacaopet',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='publicacaopet',
            name='idade',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='publicacaopet',
            name='porte',
            field=models.CharField(blank=True, choices=[('pequeno', 'Pequeno'), ('medio', 'Medio'), ('grande', 'Grande')], max_length=20),
        ),
        migrations.AddField(
            model_name='publicacaopet',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('resolvido', 'Resolvido')], default='ativo', max_length=20),
        ),
        migrations.AddField(
            model_name='publicacaopet',
            name='tipo_animal',
            field=models.CharField(blank=True, max_length=80, verbose_name='Tipo do animal'),
        ),
    ]
